# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField(default='')),
                ('summary', models.TextField(default='')),
                ('title', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_id', models.IntegerField(default=-1)),
                ('paragraph_string', models.TextField(default='')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evline_task.Novel')),
            ],
        ),
        migrations.CreateModel(
            name='Step1_Task_A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Turker_id', models.CharField(default='', max_length=30)),
                ('is_separate', models.BooleanField(default=False)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evline_task.Novel')),
                ('refer_paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evline_task.Paragraph')),
            ],
        ),
        migrations.CreateModel(
            name='Step1_Task_B',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Turker_id', models.CharField(default='', max_length=30)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evline_task.Novel')),
                ('refer_paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evline_task.Paragraph')),
            ],
        ),
        migrations.CreateModel(
            name='Summary_Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_id', models.IntegerField(default=-1)),
                ('sentence_string', models.TextField(default='')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evline_task.Novel')),
            ],
        ),
        migrations.AddField(
            model_name='step1_task_b',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evline_task.Summary_Sentence'),
        ),
    ]
