# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_id', models.IntegerField(default=-1)),
                ('begin_paragraph', models.IntegerField(default=-1)),
                ('end_paragraph', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback_Step1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(default='')),
                ('Turker_id', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback_Step2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(default='')),
                ('Turker_id', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField(default='')),
                ('summary', models.TextField(default='')),
                ('title', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_id', models.IntegerField(default=-1)),
                ('paragraph_string', models.TextField(default='')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evline_task.Novel')),
            ],
        ),
        migrations.CreateModel(
            name='Possible_Tasks_Step2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunk1', to='evline_task.Chunk')),
                ('chunk2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunk2', to='evline_task.Chunk')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evline_task.Novel')),
            ],
        ),
        migrations.CreateModel(
            name='Step1_Task_A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Turker_id', models.CharField(default='', max_length=30)),
                ('is_separate', models.BooleanField(default=False)),
                ('confidence', models.IntegerField(default=0)),
                ('context_begin_paragraph', models.IntegerField(default=-1)),
                ('context_end_paragraph', models.IntegerField(default=-1)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evline_task.Novel')),
                ('refer_paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evline_task.Paragraph')),
            ],
        ),
        migrations.CreateModel(
            name='Step1_Task_B',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Turker_id', models.CharField(default='', max_length=30)),
                ('confidence', models.IntegerField(default=0)),
                ('context_begin_paragraph', models.IntegerField(default=-1)),
                ('context_end_paragraph', models.IntegerField(default=-1)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evline_task.Novel')),
                ('refer_paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evline_task.Paragraph')),
            ],
        ),
        migrations.CreateModel(
            name='Step2_Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Turker_id', models.CharField(default='', max_length=30)),
                ('confidence', models.IntegerField(default=0)),
                ('next_chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_chunk', to='evline_task.Chunk')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evline_task.Novel')),
                ('prev_chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prev_chunk', to='evline_task.Chunk')),
            ],
        ),
        migrations.CreateModel(
            name='Summary_Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_id', models.IntegerField(default=-1)),
                ('sentence_string', models.TextField(default='')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evline_task.Novel')),
            ],
        ),
        migrations.CreateModel(
            name='TaskMarker_Step1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Turker_id', models.CharField(default='', max_length=30)),
                ('Task_id', models.CharField(default='', max_length=30)),
                ('Done', models.BooleanField(default=False)),
                ('Start_Time', models.DateTimeField()),
                ('Task_Paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evline_task.Paragraph')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evline_task.Novel')),
            ],
        ),
        migrations.AddField(
            model_name='step2_task',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evline_task.Summary_Sentence'),
        ),
        migrations.AddField(
            model_name='step1_task_b',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evline_task.Summary_Sentence'),
        ),
        migrations.AddField(
            model_name='possible_tasks_step2',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evline_task.Summary_Sentence'),
        ),
        migrations.AddField(
            model_name='chunk',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evline_task.Novel'),
        ),
        migrations.AddField(
            model_name='chunk',
            name='summary_sentence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evline_task.Summary_Sentence'),
        ),
    ]
