# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evline_task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskMarker_Step2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Turker_id', models.CharField(default='', max_length=30)),
                ('Task_id2', models.CharField(default='', max_length=30)),
                ('Done', models.BooleanField(default=False)),
                ('Start_Time', models.DateTimeField()),
                ('marked_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evline_task.Possible_Tasks_Step2')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evline_task.Novel')),
            ],
        ),
    ]
