# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evline_task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step1_task_a',
            name='confidence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='step1_task_b',
            name='confidence',
            field=models.IntegerField(default=0),
        ),
    ]
