# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evline_task', '0002_taskmarker_step2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='possible_tasks_step2',
            name='chunk1',
        ),
        migrations.RemoveField(
            model_name='possible_tasks_step2',
            name='chunk2',
        ),
        migrations.RemoveField(
            model_name='possible_tasks_step2',
            name='novel',
        ),
        migrations.RemoveField(
            model_name='possible_tasks_step2',
            name='sentence',
        ),
        migrations.RemoveField(
            model_name='taskmarker_step2',
            name='marked_task',
        ),
        migrations.DeleteModel(
            name='Possible_Tasks_Step2',
        ),
    ]
