# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evline_task', '0003_feedback_step1'),
    ]

    operations = [
        migrations.AddField(
            model_name='step1_task_a',
            name='context_begin_paragraph',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='step1_task_a',
            name='context_end_paragraph',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='step1_task_b',
            name='context_begin_paragraph',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='step1_task_b',
            name='context_end_paragraph',
            field=models.IntegerField(default=-1),
        ),
    ]
