# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evline_task', '0004_possible_tasks_step2'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmarker_step2',
            name='marked_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evline_task.Possible_Tasks_Step2'),
        ),
    ]
