# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evline_task', '0005_taskmarker_step2_marked_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='possible_tasks_step2',
            name='pts_id',
            field=models.IntegerField(default=-1),
        ),
    ]
