# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evline_task', '0006_possible_tasks_step2_pts_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback_step1',
            name='Helpfulness',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feedback_step1',
            name='Understandability',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feedback_step2',
            name='Helpfulness',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feedback_step2',
            name='Understandability',
            field=models.IntegerField(default=0),
        ),
    ]
