# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evline_task', '0008_auto_20180111_0427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step1_Split',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Turker_id', models.CharField(default='', max_length=30)),
                ('is_separate', models.BooleanField(default=False)),
                ('confidence', models.IntegerField(default=0)),
                ('reasoning', models.TextField(default='')),
                ('context_begin_paragraph', models.IntegerField(default=-1)),
                ('context_end_paragraph', models.IntegerField(default=-1)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evline_task.Novel')),
                ('refer_paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evline_task.Paragraph')),
            ],
        ),
        migrations.RenameModel(
            old_name='Step1_Task_B',
            new_name='Step1_Summary',
        ),
        migrations.RemoveField(
            model_name='step1_task_a',
            name='novel',
        ),
        migrations.RemoveField(
            model_name='step1_task_a',
            name='refer_paragraph',
        ),
        migrations.DeleteModel(
            name='Step1_Task_A',
        ),
    ]
